apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rollingupdate
  name: rollingupdate
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rollingupdate
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 75%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rollingupdate
    spec:
      containers:
      - image: nginx:1.22.0
        name: nginx
