apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: recreate
  name: recreate
spec:
  replicas: 4
  selector:
    matchLabels:
      app: recreate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: recreate
    spec:
      containers:
      - image: nginx:1.22.0
        name: nginx
