---
apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials-secret
  namespace: cert-manager
type: Opaque
# this must be base64 encoded
data:
  # secret access key base64 encoded
  secret-access-key: CHANGEME # <-- please adjust
