apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <YOURNAME>-admin-clusterrolebinding # <- please replace with YOURNAME
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: <YOURNAME>-admin # <- please replace with YOURNAME
  namespace: <YOURNAME> # <- please replace with YOURNAME
