kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-application
  labels:
    app: web-application
    workshop: workshop
spec:
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: web-application
  template:
    metadata:
      labels:
        app: web-application
        workshop: workshop
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - web-application
                topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 60
      containers:
        - name: web-application
          image: syseleven/k8s-workshop-web-application:3.0.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: web-application-config
          volumeMounts:
            - mountPath: /etc/web-application
              name: web-application-secret
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 512Mi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 1
            initialDelaySeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 1
            failureThreshold: 3
        - name: prometheus-pushgateway
          image: prom/pushgateway:v0.8.0
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 9091
              name: metrics
          livenessProbe:
            httpGet:
              path: /
              port: metrics
      volumes:
        - name: web-application-secret
          secret:
            secretName: web-application-secret
