apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: security-context-demo
  name: security-context-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-context-demo
  template:
    metadata:
      labels:
        app: security-context-demo
    spec:
      containers:
      - image: httpd:2.4.57
        imagePullPolicy: Always
        name: httpd
        securityContext:
          runAsUser: 1234
          runAsNonRoot: false
          readOnlyRootFilesystem: true
