apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-node-affinity
  labels:
    app: deployment-node-affinity
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deployment-node-affinity
  template:
    metadata:
      labels:
        app: deployment-node-affinity
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                  - linux
      containers:
        - name: nginx
          image: nginx