apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        # pod should not be scheduled on the same node
        podAntiAffinity:
          # but if it already running there, nevermind
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                # decide by these pod labels
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                        - nginx
                # this should affect node by its name
                topologyKey: "kubernetes.io/hostname"
      containers:
      - image: nginx:1.23.0
        name: nginx
