apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-demo
  labels:
    app: sidecar-container-demo
spec:
  containers:
  - image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) 'Hi I am from Sidecar container <br>' >> /var/log/index.html; sleep 5;done"]
    name: sidecar-container
    resources: {}
    volumeMounts:
    - name: var-logs
      mountPath: /var/log
  - image: nginx
    name: main-container
    resources: {}
    ports:
      - containerPort: 80
    volumeMounts:
    - name: var-logs
      mountPath: /usr/share/nginx/html
  dnsPolicy: Default
  # wir erstellen ein besondere Art von Volume
  # Container in einem Pod teilen Netzwerk und Storage
  # Beide Container mounten das Volume, jedoch unter unterschiedlichen Pfaden
  volumes:
  - name: var-logs
    emptyDir: {}
