apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-apache
  name: php-apache
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: php-apache
  type: ClusterIP
status:
  loadBalancer: {}
