apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: daemonset-demo
  name: daemonset-demo
spec:
  selector:
    matchLabels:
      app: daemonset-demo
  template:
    metadata:
      labels:
        app: daemonset-demo
    spec:
      containers:
      - image: nginx
        name: nginx
